loglevel = "DEBUG"
logfile = ""
repro_file = ""
[dataset]
root = "platform:MSV000079284"
bigscape_cutoff = 30
[dataset.overrides]
[scoring]
[scoring.metcalf]
cutoff = 1.0
enabled = true
standardised = true
[scoring.hg]
prob = 0.99
enabled = false
[scoring.likescore]
cutoff = 0.5
enabled = false
