name: Test the dashboard

on:
    push:
      branches:
        - main
      paths:
        - src/**
        - tests/**
        - setup.py
        - .github/workflows/build.yml
    pull_request:
      paths:
        - app/**
        - tests/**
        - .github/workflows/build.yml
      types:
        - opened
        - reopened
        - synchronize
        - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        pip install pytest
        pytest tests
