name: Test the dashboard

on:
  push:
    branches:
      - main
    paths:
      - app/**
      - tests/**
      - pyproject.toml
      - .github/workflows/test.yml
  pull_request:
    paths:
      - app/**
      - tests/**
      - pyproject.toml
      - .github/workflows/test.yml
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m venv venv
        source venv/bin/activate
        pip install -e ".[dev]"

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest tests